version: '3'
services:
  jupyter:
    image: continuumio/anaconda3:latest
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/opt/notebooks
    environment:
      - JUPYTER_ENABLE_LAB=yes
    command: ["jupyter", "lab", "--ip='0.0.0.0'", "--port=8888", "--no-browser", "--allow-root", "--NotebookApp.token=''", "--NotebookApp.password=''"]
